config/routes.rb
Rails.application.routes.draw do
  resources :chores
  resources :purchases
  resources :purchase_categories, only: [:show, :new, :create, :edit, :update]
  resources :todo_solutions, only: [:create, :destroy]
  resources :users
  resources :tasks, only: [:destroy]
  resources :todos, only: [:new, :show, :index, :create, :update, :destroy]
  resources :todo_categories, only: [:new,:edit,:create,:update, :show]
  resources :refunds, only: [:new,:index,:create]
  resource :session, only: [:new, :create, :destroy]

  get 'index', to: 'index#index'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'addchore', to: 'chore_users#add_to_user'

  delete 'removechore', to: 'chore_users#remove_from_user'

  post 'publishchore', to: 'chores#publish'

  post 'completechore/:id', to: 'chores#complete', as: 'completechore'

  post 'confirmrefund', to: 'refunds#confirm'
  post 'cancelrefund', to: 'refunds#cancel'

  post 'manage/activateuser/:id', to: 'users#activate'
  get 'manage/users', to: 'users#manage'

  get 'users/:id/chores', to: 'users#chores', as: 'userchores'
  get 'users/:id/todos', to: 'users#todos', as: 'usertodos'
  get 'users/:id/purchases', to: 'users#purchases', as: 'userpurchases'
  get 'users/:id/refunds', to: 'users#refunds', as: 'userrefunds'

  get 'feed', to: 'index#feed'
  get 'toplist', to: 'index#toplist'
  root 'index#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :chore_users
  has_many :tasks
  has_many :chores, through: :chore_users
  has_many :purchases
  has_many :xps, dependent: :destroy
  has_many :todo_users
  has_many :todos, through: :todo_users

  validates :username, uniqueness: true, length: { minimum: 3 }
  validates :name, length: {minimum: 3}

  scope :active, -> { where deactivated:[nil,false]}
  scope :deactivated, -> { where deactivated:true }

  has_secure_password

  def to_s
    self.name
  end

  def purchase_sum
    self.purchases.sum(:price)
  end

  def xp_total
    self.xps.sum(:points)
  end

  def xp_total_range from_ago
    self.xps.where("created_at > ?", from_ago).sum(:points)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_that_signed_in
  before_action :ensure_that_admin, only: [:manage, :destroy, :create, :activate]
  before_action :set_user, only: [:show, :destroy, :update, :activate, :edit, :todos, :chores, :purchases]
  before_action :ensure_that_user, only: [:todos, :chores, :refunds]
  before_action :ensure_update_permission, only: [:update]

  def show
    @chores = Chore.sort_by_user_task_count(@user)
  end

  def todos
    @todos = Todo.where(creator_id: @user.id).where(private: true).where(todo_solution_id: nil).paginate(page: params[:page]).order(:due)
    @comptodos = Todo.where(creator_id: @user.id).where(private: true).where.not(todo_solution_id: nil).paginate(page: params[:comppage]).order(:due)
  end

  def chores
    @chores = Chore.where(private:true).where(creator_id:current_user.id)
  end

  def purchases
    @purchases = @user.purchases
    @categories = PurchaseCategory.all
    @users = User.active
  end

  def refunds
    @refunds = Refund.where(receiver_id: current_user.id).where(confirmed: false)
    @pendrefunds = Refund.where(payer_id: current_user.id).where(confirmed: false)
  end

  def manage
    @users = User.active
    @dusers = User.deactivated
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    startingbalance = Purchase.new(purchase_category_id: 1, price: average_purchase, description: 'Starting balance for added user')
    if @user.save
      startingbalance.user_id = @user.id
      @user.purchases << startingbalance
      redirect_to :back, notice: 'New user added.'
    else
      redirect_to :back, alert: 'Error creating new user'
    end
  end

  def destroy
    if @user.update(deactivated:true)
      redirect_to :back, notice: 'User deactivated successfully.'
    else
      redirect_to :back, alert: 'Error destroying user.'
    end
  end

  def update
    if @user.update(update_params)
      redirect_to :back, notice: 'User information updated successfully'
    else
      if @user == current_user
        render :edit
      else
        render :manage, alert: 'Something went wrong'
      end
    end
  end

  def activate
    if @user.update(deactivated: false)
      redirect_to :back, notice: 'User activated.'
    else
      redirect_to :back, alert: 'Something went wrong'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :admin)
  end

  def update_params
    if current_user.admin?
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    else
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
  end

  def ensure_that_user
    redirect_to :root, notice: 'Not your list!' if not current_user == @user
  end

  def ensure_update_permission
    current_user == @user || current_user.admin?
  end
end

app/views/users/_chore_list.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
    </tr>
  </thead>

  <tbody>
    <% chores.each do |chore| %>
    <tr>
      <td>
         <%= link_to chore.name, chore_path(chore) %>
      </td>
      <td>
        <%= chore.priority %>
      </td>
      <td><%= link_to 'Show', chore,class:"btn btn-primary" %></td>
      <td><%= link_to 'Edit', edit_chore_path(chore),class:"btn btn-primary" %></td>
      <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      <% if not current_user.chores.include? chore %>
      <td><%= link_to 'Add to frontpage', addchore_path(chore), method: :post, class:"btn btn-primary" %></td>
      <% else %>
      <td><%= link_to 'Remove from frontpage', removechore_path(chore), method: :delete, class:"btn btn-danger" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_chore_stats.html.erb
<table class="table table-hover">
  <thead>
    <th>
      Chore
    </th>
    <th>
      Times done
    </th>
  </thead>
  <tbody>
    <% chores.each do |chore| %>
    <tr>
      <td>
        <%= Chore.find(chore[0]) %>
      </td>
      <td>
        <%= chore[1] %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>





<%= f.text_field :name %>
<% if @user.new_record? %>
<%= f.text_field :username %>
<% end %>
<%= f.password_field :password %>
<%= f.password_field :password_confirmation %>



<% end %>

app/views/users/_pending_refundlist.html.erb
<% if not @pendrefunds.empty? %>
 <h2>Sent refunds</h2>
  <table class="table table-hover" >
  <thead>
    <tr>
      <th>
        To
      </th>
      <th>
        Amount
      </th>
      <th>
        Cancel
      </th>
    </tr>
  </thead>
  <tbody>
    <% @pendrefunds.each do |refund| %>
    <tr>
      <td>
        <%= User.find(refund.receiver_id).to_s %>
      </td>
      <td>
        <%= refund.amount %>
      </td>
      <td>
        <%= link_to 'Cancel', cancelrefund_path(refund), method: :post, class:"btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>


<% end %>

app/views/users/_refundlist.html.erb
<% if not @refunds.empty? %>
<h2>Uncorfimed refunds</h2>
  <table class="table table-hover" >
  <thead>
    <tr>
      <th>
        From
      </th>
      <th>
        Amount
      </th>
      <th>
        Confirm
      </th>
      <th>
        Reject
      </th>
    </tr>
  </thead>
  <tbody>
    <% @refunds.each do |refund| %>
    <tr>
      <td>
        <%= User.find(refund.payer_id).to_s %>
      </td>
      <td>
        <%= refund.amount %>
      </td>
      <td>
        <%= link_to 'Confirm', confirmrefund_path(refund), method: :post, class:"btn btn-primary" %>
      </td>
      <td>
        <%= link_to 'Reject', cancelrefund_path(refund), method: :post, class:"btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>


<% end %>

app/views/users/_todo_list.html.erb
<%= will_paginate todos, renderer: BootstrapPagination::Rails %>

<table class="table table-hover">
  <thead>
    <th>
      Title
    </th>
    <th>
      Creator
    </th>
    <th>
      Due in
    </th>
  </thead>
  <tbody>
    <% todos.each do |todo| %>
    <tr>
      <td>
        <%= link_to todo.title, todo_path(todo) %>
      </td>
      <td>
        <%= User.find(todo.creator_id).to_s %>
      </td>
      <td>
        <%= todo.due %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/chores.html.erb
<h1>Your own chores</h1>

<%= render 'chores/list', chores:@chores %>

app/views/users/edit.html.erb
<h2>Edit your information</h2>

<%= bootstrap_form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %>
    prohibited this info from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.text_field :name %>
<%= f.password_field :password %>
<%= f.password_field :password_confirmation %>

<%= f.submit :class => 'btn btn-primary' %>

<% end %>

app/views/users/manage.html.erb
<h1>Users list</h1>

<table class="table table-hover">
  <thead>
    <th>
      Username
    </th>
    <th>
      Name
    </th>
    <th>
      Password
    </th>
    <th>
      Password_confirmation
    </th>
    <th>
      Admin?
    </th>
    <th>
      Save
    </th>
    <th>
      Delete
    </th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <%= form_for(user) do |f| %>
    <tr>
      <td>
        <b><%= user.username %></b>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
      <td>
        <%= f.password_field :password %>
      </td>
      <td>
        <%= f.password_field :password_confirmation %>
      </td>
      <td>
        <%= f.check_box :admin %>
      </td>
      <td>
        <%= f.submit class:"btn btn-success" %>
      </td>
        <% end %>
      <td>
        <% if not user == current_user %>
        <%= link_to 'Deactivate User', user_path(user), method: :delete, data: { confirm: 'Are you sure you want to deactivate '+user.name+'?'}, class:"btn btn-danger" %>
        <% end %>
      </td>
    </tr>

    <% end %>
    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this chore from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <tr>
      <td>
        <b>NEW USER</b>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :username %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
      <td>
        <%= f.password_field :password %>
      </td>
      <td>
        <%= f.password_field :password_confirmation %>
      </td>
      <td>
        <%= f.check_box :admin %>
      </td>
      <td>
        <%= f.submit class:"btn btn-success" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>Deactivated users list</h2>
<table class="table table-hover">
  <thead>
    <th>
      Username
    </th>
    <th>
      Name
    </th>
    <th>
      Activate!
    </th>
  </thead>
  <tbody>
    <% @dusers.each do |user| %>
    <tr>
      <td>
        <%= user.username %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= link_to 'Activate', 'activateuser/'+user.id.to_s, method: :post, class:"btn btn-primary" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= render 'form' %>

app/views/users/purchases.html.erb
<h1><%= @user.to_s %>'s purchases</h1>

<%= render 'purchases/selection_menu', categories:@categories, users: @users %>

<%= render 'purchases/list', purchases: @purchases %>

app/views/users/refunds.html.erb
<h1>Your refunds</h1>

<div class="col-md-5">

  <%= render 'refundlist' %>

</div>
<div class="col-md-5">

  <%= render 'pending_refundlist' %>

</div>

app/views/users/show.html.erb
<div class="col-md-10 col-centered">
  <h1><%= @user.name %></h1>

  <% if @user == current_user %>
  <% end %>
</div>
<div class="col-md-5 col centered">
  <%= render 'chore_stats', chores:@chores %>
</div>

app/views/users/todos.html.erb
<h1>Your own todos</h1>

<h2>TODO</h2>
<%= render 'todos/list', todos:@todos %>

<h2>DONE</h2>
<%= render 'todos/completed_list', todos:@comptodos %>