config/routes.rb
Rails.application.routes.draw do
  resources :chores
  resources :purchases
  resources :purchase_categories, only: [:show, :new, :create, :edit, :update]
  resources :todo_solutions, only: [:create, :destroy]
  resources :users
  resources :tasks, only: [:destroy]
  resources :todos, only: [:new, :show, :index, :create, :update, :destroy]
  resources :todo_categories, only: [:new,:edit,:create,:update, :show]
  resources :refunds, only: [:new,:index,:create]
  resource :session, only: [:new, :create, :destroy]

  get 'index', to: 'index#index'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'addchore', to: 'chore_users#add_to_user'

  delete 'removechore', to: 'chore_users#remove_from_user'

  post 'publishchore', to: 'chores#publish'

  post 'completechore/:id', to: 'chores#complete', as: 'completechore'

  post 'confirmrefund', to: 'refunds#confirm'
  post 'cancelrefund', to: 'refunds#cancel'

  post 'manage/activateuser/:id', to: 'users#activate'
  get 'manage/users', to: 'users#manage'

  get 'users/:id/chores', to: 'users#chores', as: 'userchores'
  get 'users/:id/todos', to: 'users#todos', as: 'usertodos'
  get 'users/:id/purchases', to: 'users#purchases', as: 'userpurchases'
  get 'users/:id/refunds', to: 'users#refunds', as: 'userrefunds'

  get 'feed', to: 'index#feed'
  get 'toplist', to: 'index#toplist'
  root 'index#index'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :ensure_that_signed_in

  def new
    @purchase = Purchase.new
    @categories = PurchaseCategory.all.where.not(id: 1)
  end

  def index
    @purchases = Purchase.paginate(page: params[:page]).order(created_at: :desc)
    @categories = PurchaseCategory.all
    @users = User.active
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    if @purchase.save
      TelegramApi.send_to_channel '' + current_user.to_s + ' has just bought ' + @purchase.description + '. Cost: ' + @purchase.price.to_s + " €. Category: " + @purchase.purchase_category.to_s + ''
      redirect_to :root, notice: 'Purchase saved'
    else
      @categories = PurchaseCategory.all.where.not(id: 1)
      render :new
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])
    if @purchase.user == current_user
      @purchase.destroy
      redirect_to purchases_path, notice: 'Purchase deleted succesfully'
    else
      redirect_to :root, notice: 'Cannot delete purchase made by someone else'
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:purchase_category_id, :price, :description)
  end

end

app/views/purchases/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>
        User
      </th>
      <th>
        Description
      </th>
      <th>
        Category
      </th>
      <th>
        Price
      </th>
      <th>
        Date
      </th>
      <th>

      </th>
    </tr>
  </thead>
  <tbody>
    <% purchases.each do |purchase| %>
    <tr>
      <td>
        <%= purchase.user %>
      </td>
      <td>
        <%= purchase.description %>
      </td>
      <td>
        <% if purchase.purchase_category.nil? %>
          Refund
        <% end %>
        <%= purchase.purchase_category %>
      </td>
      <td>
        <%= purchase.price %>
      </td>
      <td>
        <%= purchase.created_at %>
      </td>
      <% if current_user == purchase.user %>
      <td>
        <%= link_to 'Delete', purchase, method: :delete, data: {confirm: 'Are you sure you want to delete the purchase?'}, class:'btn btn-danger' %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/purchases/_selection_menu.html.erb
<div class="row">
<div class="col-md-5">

<div class="dropdown div-inline">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
  Select Category
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to 'Show all', purchases_path %>
    </li>
    <% categories.each do |cat| %>
    <li>
      <%= link_to cat, purchase_category_path(cat) %>
    </li>
    <%end%>
  </ul>
</div>
<b>OR</b>
<div class="dropdown div-inline">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
  Select User
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to 'Show all', purchases_path %>
    </li>
    <% users.each do |user| %>
    <li>
      <%= link_to user, userpurchases_path(user) %>
    </li>
    <% end %>
</div>

</div>
</div>

app/views/purchases/index.html.erb
<h1> Purchases list </h1><br />

      <%= render 'selection_menu', categories: @categories, users:@users %>




<%= render 'list', purchases: @purchases %>

<%= will_paginate @purchases, renderer: BootstrapPagination::Rails %>

app/views/purchases/new.html.erb
<%= bootstrap_form_for(@purchase) do |f| %>
<% if @purchase.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@purchase.errors.count, "error") %>
    prohibited this purchase from being saved:</h2>

  <ul>
    <% @purchase.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<h1>New Purchase</h1>
<%= f.text_field :description %>
<%= f.number_field :price, :class => 'text_field', :step => '0.01' %>
<%= f.select :purchase_category_id, options_from_collection_for_select(@categories, :id, :to_s) %>

<%= f.submit  :class => 'btn btn-success' %>

<% end %>
<br />
<h2>Create New Category:</h2>
<br />
  <%= link_to 'New Purchase Category', new_purchase_category_path, class:"btn btn-primary" %>