config/routes.rb
Rails.application.routes.draw do
  resources :chores
  resources :purchases
  resources :purchase_categories, only: [:show, :new, :create, :edit, :update]
  resources :todo_solutions, only: [:create, :destroy]
  resources :users
  resources :tasks, only: [:destroy]
  resources :todos, only: [:new, :show, :index, :create, :update, :destroy]
  resources :todo_categories, only: [:new,:edit,:create,:update, :show]
  resources :refunds, only: [:new,:index,:create]
  resource :session, only: [:new, :create, :destroy]

  get 'index', to: 'index#index'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'addchore', to: 'chore_users#add_to_user'

  delete 'removechore', to: 'chore_users#remove_from_user'

  post 'publishchore', to: 'chores#publish'

  post 'completechore/:id', to: 'chores#complete', as: 'completechore'

  post 'confirmrefund', to: 'refunds#confirm'
  post 'cancelrefund', to: 'refunds#cancel'

  post 'manage/activateuser/:id', to: 'users#activate'
  get 'manage/users', to: 'users#manage'

  get 'users/:id/chores', to: 'users#chores', as: 'userchores'
  get 'users/:id/todos', to: 'users#todos', as: 'usertodos'
  get 'users/:id/purchases', to: 'users#purchases', as: 'userpurchases'
  get 'users/:id/refunds', to: 'users#refunds', as: 'userrefunds'

  get 'feed', to: 'index#feed'
  get 'toplist', to: 'index#toplist'
  root 'index#index'

end

app/models/purchase_category.rb
class PurchaseCategory < ActiveRecord::Base
  has_many :purchases

  validates :name, presence: true, length: { in: 2..30 }

  def to_s
    self.name
  end
end

app/controllers/purchase_categories_controller.rb
class PurchaseCategoriesController < ApplicationController
before_action :set_purchase_category, only: [:show, :edit, :update]
before_action :ensure_that_signed_in


def show
  @purchases = @purchase_category.purchases.paginate(:page => params[:page]).order(created_at: :desc)
  @categories = PurchaseCategory.all
  @users = User.active
end

def new
  @purchase_category = PurchaseCategory.new
end
def edit
end
def update
  if @purchase_category.update(purchase_category_params)
    redirect_to :back, notice: 'PurchaseCategory updated succesfully'
  else
    redirect_to :root, alert: 'Something went wrong'
  end
end
def create
  @cat = PurchaseCategory.new(purchase_category_params)
  if @cat.save
    redirect_to :root, notice: 'New purchase category added.'
  else
    render :new
  end
end

private

def set_purchase_category
  @purchase_category = PurchaseCategory.find(params[:id])
end

def purchase_category_params
  params.require(:purchase_category).permit(:name)
end

end

app/views/purchase_categories/_category_menu.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
  Select Category
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to 'Show all', purchases_path %>
    </li>
    <% categories.each do |cat| %>
    <li>
      <%= link_to cat, purchase_category_path(cat) %>
    </li>
    <%end%>
  </ul>
</div>

app/views/purchase_categories/_form.html.erb
<%= bootstrap_form_for(@purchase_category) do |f| %>
<% if @purchase_category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@purchase_category.errors.count, "error") %>
    prohibited this purchase category from being saved:</h2>

  <ul>
    <% @purchase_category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.text_field :name %>
<%= f.submit :class => 'btn btn-success' %>

<% end %>

app/views/purchase_categories/edit.html.erb
<h1>Edit Purchase Category</h1>

<%= render 'form' %>

app/views/purchase_categories/new.html.erb
<h1>New Purchase Category</h1>

<%= render 'form' %>

app/views/purchase_categories/show.html.erb
<h1><%= @purchase_category.name %> <%= link_to 'Edit', edit_purchase_category_path(@purchase_category), class:'btn btn-primary'%></h1><br/>

    <%= render 'purchases/selection_menu', categories: @categories, users:@users%>







<table class="table table-hover">
  <thead>
    <tr>
      <th>
        User
      </th>
      <th>
        Description
      </th>
      <th>
        Category
      </th>
      <th>
        Price
      </th>
      <th>
        Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @purchases.each do |purchase| %>
    <tr>
      <td>
        <%= purchase.user %>
      </td>
      <td>
        <%= purchase.description %>
      </td>
      <td>
        <%= purchase.purchase_category %>
      </td>
      <td>
        <%= purchase.price %>
      </td>
      <td>
        <%= purchase.created_at %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @purchases, renderer: BootstrapPagination::Rails %>