config/routes.rb
Rails.application.routes.draw do
  resources :chores
  resources :purchases
  resources :purchase_categories, only: [:show, :new, :create, :edit, :update]
  resources :todo_solutions, only: [:create, :destroy]
  resources :users
  resources :tasks, only: [:destroy]
  resources :todos, only: [:new, :show, :index, :create, :update, :destroy]
  resources :todo_categories, only: [:new,:edit,:create,:update, :show]
  resources :refunds, only: [:new,:index,:create]
  resource :session, only: [:new, :create, :destroy]

  get 'index', to: 'index#index'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'addchore', to: 'chore_users#add_to_user'

  delete 'removechore', to: 'chore_users#remove_from_user'

  post 'publishchore', to: 'chores#publish'

  post 'completechore/:id', to: 'chores#complete', as: 'completechore'

  post 'confirmrefund', to: 'refunds#confirm'
  post 'cancelrefund', to: 'refunds#cancel'

  post 'manage/activateuser/:id', to: 'users#activate'
  get 'manage/users', to: 'users#manage'

  get 'users/:id/chores', to: 'users#chores', as: 'userchores'
  get 'users/:id/todos', to: 'users#todos', as: 'usertodos'
  get 'users/:id/purchases', to: 'users#purchases', as: 'userpurchases'
  get 'users/:id/refunds', to: 'users#refunds', as: 'userrefunds'

  get 'feed', to: 'index#feed'
  get 'toplist', to: 'index#toplist'
  root 'index#index'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :users, through: :chore_users

  attr_accessor :priorities

  validates :name, presence: true, length: { in: 2..30 }

  scope :pub, -> { where.not(private:true)}

  def to_s
    name
  end

  def prioritycalc(multiplier)
    case multiplier
    when 'hours'
      self.priority = priority
    when 'days'
      self.priority = priority * 24
    when 'weeks'
      self.priority = priority * 24 * 7
    end
  end

  def add_to_every_user
    User.active.each do |user|
      ChoreUser.create(user_id: user.id, chore_id: id)
    end
  end

  def weekly_average_task_count
    weeks = ((Time.now - created_at) / 1.week.seconds)
    weeks = 1 if weeks < 1
    if !tasks.empty?
      '%.2f' % (tasks.count / weeks)
    else
      0
    end
  end

  def telegram_message user
    if self.completion_text.nil?
      ""+user.to_s+" has just finished "+self.name+""
    else
      ""+user.to_s+" "+self.completion_text
    end
  end

  def complete user
    task  = Task.new(chore_id:self.id, user_id:user.id)
    if task.save
      if not self.private
        TelegramApi.send_to_channel telegram_message(user)
        xp = Xp.create source:"Chore: "+task.chore.name, points:task.chore.reward
        user.xps << xp
      end
      true
    else
      false
    end
  end

  def self.sort_by_user_task_count user
    chores = Chore.pub
    counts = {}
    chores.each do |chore|
      count = Task.where(user_id:user.id, chore_id:chore.id).count
      counts[chore.id] = count if count != 0
    end
    counts.sort_by {|k,v| v}.reverse
  end

  def sort_users_by_task_count
    @users = User.active
    maarat = {}
    @users.each do |user|
      maarat[user.id] = Task.where(user_id:user.id, chore_id:self.id).count
    end
    maarat.sort_by {|k,v| v}.reverse
  end


end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy, :complete]
  before_action :ensure_that_signed_in

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.where('private=? OR private=?',false,nil)
    @privatechores = Chore.where(private:true, creator_id:current_user.id)
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    if @chore.private && current_user.id != @chore.creator_id
      redirect_to :root, notice: 'That chore is private'
    end
    @users = @chore.sort_users_by_task_count
    @tasks = Task.where(chore:@chore).order(created_at: :desc).limit(10)
  end

  # GET /chores/new
  def new
    @chore = Chore.new
    @priorities = ['hours', 'days', 'weeks']
  end

  # GET /chores/1/edit
  def edit
    if @chore.private && current_user.id != @chore.creator_id
        redirect_to :root, notice: 'That chore is private'
    end
     @priorities = ['hours', 'days', 'weeks']
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)
    @chore.prioritycalc(params[:chore][:priorities])
    @chore.creator_id = current_user.id
    respond_to do |format|
      if @chore.save
        @chore.add_to_every_user if not @chore.private?
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
      @chore.destroy
      respond_to do |format|
        format.html { redirect_to chores_url, notice: 'Chore was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  def complete
    if @chore.complete current_user
      redirect_to :back, notice: 'Nicely done'
    else
      redirect_to :root, notice: 'Something went wrong, try again'
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:name, :priority, :reward, :private, :completion_text, :priorities)
    end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<div class="col-md-10">


<%= bootstrap_form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name %>
    <div class="row">
      <div class="col-md-5">
        <%= f.number_field :priority %>
      </div>
      <div class="col-md-5">
          <%= f.label '     '%>
          <%= f.select :priorities, @priorities, hide_label: true %>
      </div>

    </div>

    <%= f.number_field :reward %>
    <p>
      (Optional) add a completion text that gets send to the Telegram channel (if set).
      Format: "username" "text of your choosing"
    </p>
    <%= f.text_field :completion_text %>
    <% if @chore.new_record? %>
    <%= f.check_box :private %>
    <% elsif current_user.id == @chore.creator_id %>
    <%= f.check_box :private %>
    <% end %>
    <%= f.submit :class => 'btn btn-success'  %>

<% end %>
</div>

app/views/chores/_list.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>Reward points</th>
    </tr>
  </thead>

  <tbody>
    <% chores.each do |chore| %>
    <tr>
      <td>
         <%= link_to chore.name, chore_path(chore) %>
      </td>
      <td>
        <% if not chore.priority.nil? %>
        <%= distance_of_time_in_words(chore.priority.hours) %>
        <% end %>
      </td>
      <td>
        <%= chore.reward %>
      </td>
      <td>
        <%= link_to 'Complete', completechore_path(chore), class:"btn btn-primary", method: :post%>
      </td>
      <% if not current_user.chores.include? chore %>
      <td><%= link_to 'Add to frontpage', addchore_path(chore), method: :post, class:"btn btn-primary" %></td>
      <% else %>
      <td><%= link_to 'Remove from frontpage', removechore_path(chore), method: :delete, class:"btn btn-danger" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/chores/_tasklist.html.erb
<table class="table">
  <thead>
    <tr>
      <th>
        By
      </th>
      <th>
        At
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% tasks.each do |task| %>
    <tr>
      <td>
        <%= task.user %>
      </td>
      <td>
        <%= task.created_at %>
      </td>
      <td>
        <% if task.user == current_user || current_user.admin? %>
        <%= link_to 'Delete',task, method: :delete, class:'btn btn-danger', data: {confirm: 'Are you sure you want to remove selected task?'} %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form' %>


<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Chores</h1>
<%= render 'list', chores: @chores %>

<h1>User Chores</h1>
<%= render 'list', chores: @privatechores %>
<br>

<%= link_to 'New Chore', new_chore_path, class:"btn btn-primary" %>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

app/views/chores/show.html.erb
<div class="row">
  <div class="col-md-5 col-centered">
    <h2><%= @chore.name %></h2>
    <p>
      Created by:
      <%= User.find(@chore.creator_id) %>
    </p>

    <%= link_to 'Complete', completechore_path(@chore), class:"btn btn-primary", method: :post%>

    <h3>Details</h3>
    <ul>
      <% if not @chore.reward.nil? %>
      <li>
        Rewards
        <%= @chore.reward %>
        points
      </li>
      <% end %>
      <% if not @chore.priority.nil? %>
      <li>
        Should be done every
        <%= distance_of_time_in_words(@chore.priority.hours) %>
      </li>
      <% end %>
      <li>
        Has been done a total of
        <%= @chore.tasks.count %>
        times since
        <%= @chore.created_at %>.
      </li>
      <li>
        Which means - on average -
        <%= @chore.weekly_average_task_count %>
        times per week.
      </li>

    </ul>
    <% if not @chore.private? %>
    <h3>Statistics</h3>
    <table class="table">
      <thead>
        <th>User</th>
        <th>Has completed it</th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= User.find(user.first).to_s %>
          </td>
          <td>
            <%= user.last %>
            times
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <% end %>

  </div>
</div>
<div class="row">
  <div class="col-md-5 col-centered">
    <%= link_to 'Edit', edit_chore_path(@chore), class:"btn btn-primary"%>
    <%= link_to 'Destroy', @chore, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Back', chores_path, class:"btn btn-primary" %>
    <br />
  </div>
</div>

<div class="row">
  <div class="col-md-5 col-centered">
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" href="#collapse1">Recent completions</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <div class="panel-body">

            <%= render 'tasklist', tasks: @tasks %>
          </div>
          <div class="panel-footer"></div>
        </div>
      </div>
    </div>
  </div>
</div>